
import os
import tempfile
import httpx
import discord
from discord import app_commands
from discord.ext import commands
from backend.config import settings
from bot.api import BACKEND_URL, api_client

class MemeSlash(commands.Cog):
    def __init__(self, bot: commands.Bot):
        self.bot = bot

    @app_commands.command(name="meme", description="Generate a text-overlay meme instantly (zero API cost)")
    @app_commands.describe(
        top_text="Top text caption for the meme",
        bottom_text="Bottom text caption for the meme",
        bg_color="Background color hex code (e.g. #1e1e2e or #ff5555)"
    )
    async def make_meme(
        self,
        interaction: discord.Interaction,
        top_text: str = "",
        bottom_text: str = "",
        bg_color: str = "#1e1e2e"
    ):
        await interaction.response.defer(thinking=True)
        if not top_text and not bottom_text:
            top_text = "WHEN THE MEME HAS"
            bottom_text = "NO CAPTIONS"

        payload = {
            "top_text": top_text,
            "bottom_text": bottom_text,
            "bg_color": bg_color
        }

        try:
            async with api_client(timeout=15.0) as client:
                res = await client.post(f"{BACKEND_URL}/api/media/meme", json=payload)
                if res.status_code != 200:
                    await interaction.followup.send(f"⚠️ Meme generation error: {res.text}")
                    return

                import tempfile
                temp_img_path = os.path.join(tempfile.gettempdir(), f"discord_meme_{os.urandom(4).hex()}.png")
                with open(temp_img_path, "wb") as f:
                    f.write(res.content)

                discord_file = discord.File(temp_img_path, filename="zauq_meme.png")
                embed = discord.Embed(
                    title="🖼️ Generated Meme",
                    color=discord.Color.magenta()
                )
                embed.set_image(url="attachment://zauq_meme.png")
                embed.set_footer(text=f"Generated by @{interaction.user.name}")

                await interaction.followup.send(embed=embed, file=discord_file)
                try:
                    os.remove(temp_img_path)
                except Exception:
                    pass

        except Exception as e:
            await interaction.followup.send(f"❌ Error generating meme: {e}")

async def setup(bot: commands.Bot):
    await bot.add_cog(MemeSlash(bot))
