import re
import httpx
from typing import List, Dict, Any, AsyncGenerator, Optional
from backend.config import settings

def sanitize_response_output(text: str) -> str:
    """
    Strips internal thinking scratchpads (<thought>...</thought>), <think>...</think>,
    CoT planning notes, and Draft listings (Draft 1, Draft 2, Draft 3) generated by
    Gemma and open models.
    """
    if not text:
        return text

    # 1. Strip XML thought blocks <thought>...</thought> and <think>...</think>
    text = re.sub(r"<thought>.*?</thought>", "", text, flags=re.DOTALL).strip()
    text = re.sub(r"<think>.*?</think>", "", text, flags=re.DOTALL).strip()

    # 2. If Gemma/Open models output internal draft listings (Draft 1, Draft 2, Draft 3...)
    if "Draft 3" in text or "Draft 2" in text or "Draft 1" in text:
        matches = list(re.finditer(r"(?:\*+\s*)?Draft\s*\d+[^\n:]*:\s*\*?\s*(.*?)(?=\n\s*\*+\s*Draft|\Z)", text, flags=re.DOTALL | re.IGNORECASE))
        if matches:
            last_draft = matches[-1].group(1).strip()
            if last_draft:
                text = last_draft

    return text

def format_grounding_citations(text: str, grounding_meta: Optional[Dict[str, Any]]) -> str:
    """
    Extracts web search citations from Google Search Grounding metadata
    and appends clean markdown reference links to the output.
    """
    if not grounding_meta:
        return text

    chunks = grounding_meta.get("groundingChunks", [])
    if not chunks:
        return text

    sources = []
    seen_uris = set()

    for chunk in chunks:
        web = chunk.get("web", {})
        uri = web.get("uri")
        title = web.get("title") or uri
        if uri and uri not in seen_uris:
            seen_uris.add(uri)
            # Truncate title if excessively long
            clean_title = (title[:60] + "...") if len(title) > 60 else title
            sources.append(f"• [{clean_title}]({uri})")

    if sources:
        citations_block = "\n\n🌐 **Web Sources & Grounding:**\n" + "\n".join(sources[:5])
        return text + citations_block

    return text

from backend.agent.types import AgentModelTurn, ToolCall, ToolResultMessage
from backend.models.tool_schemas import to_gemini_tools, normalize_tool_call_name
from backend.tools.aliases import canonical_to_alias

class GeminiClient:
    def __init__(self, api_key: str = None):
        self.api_key = api_key or settings.GEMINI_API_KEY
        self.default_model = "gemini-2.5-flash"

    def _prepare_payload(
        self,
        messages: List[Dict[str, Any]],
        system_prompt: Optional[str] = None,
        temperature: float = 0.7,
        media_parts: Optional[List[Dict[str, str]]] = None,
        image_parts: Optional[List[Dict[str, str]]] = None,
        enable_search: bool = False,
        thinking_enabled: bool = False,
        tools: Optional[List[Any]] = None,
    ) -> Dict[str, Any]:
        contents = []
        all_media = (media_parts or []) + (image_parts or [])

        for idx, raw_msg in enumerate(messages):
            msg = raw_msg.to_dict() if isinstance(raw_msg, ToolResultMessage) else raw_msg
            msg_role = msg.get("role", "user")

            # 1. Tool result message (fed back after function execution)
            if msg_role in ["tool", "function"]:
                name = msg.get("name") or msg.get("tool_name") or ""
                alias = canonical_to_alias(name) if "." in name else name
                content_val = msg.get("content", "")
                contents.append({
                    "role": "function",
                    "parts": [{
                        "functionResponse": {
                            "name": alias,
                            "response": {"name": alias, "content": str(content_val)}
                        }
                    }]
                })
                continue

            # 2. Assistant message with prior tool calls
            if msg_role in ["model", "assistant"] and msg.get("tool_calls"):
                parts = []
                if msg.get("content"):
                    parts.append({"text": str(msg["content"])})
                for tc in msg.get("tool_calls", []):
                    tc_name = tc.get("name", "") if isinstance(tc, dict) else tc.name
                    tc_alias = canonical_to_alias(tc_name) if "." in tc_name else tc_name
                    tc_args = tc.get("arguments", {}) if isinstance(tc, dict) else tc.arguments
                    parts.append({"functionCall": {"name": tc_alias, "args": tc_args}})
                contents.append({"role": "model", "parts": parts})
                continue

            # 3. Standard text & multimodal user / model turn
            role = "user" if msg_role in ["user", "system"] else "model"
            parts = [{"text": str(msg.get("content", ""))}]

            # Attach multimodal media parts (Images and Audio) to the final user message
            if idx == len(messages) - 1 and role == "user" and all_media:
                for item in all_media:
                    mime = item.get("mime_type") or ("image/png" if item.get("type") == "image" else "audio/ogg")
                    b64_data = item.get("bytes_b64", "")
                    if b64_data:
                        parts.append({
                            "inlineData": {
                                "mimeType": mime,
                                "data": b64_data
                            }
                        })

            contents.append({
                "role": role,
                "parts": parts
            })

        # Thinking mode uses a dedicated thinking budget; reserve enough tokens for output
        thinking_budget = 16384 if thinking_enabled else None

        payload: Dict[str, Any] = {
            "contents": contents,
            "generationConfig": {
                "temperature": temperature,
                "maxOutputTokens": 65536
            }
        }

        if thinking_enabled and thinking_budget:
            payload["generationConfig"]["thinkingConfig"] = {
                "thinkingBudget": thinking_budget
            }

        if system_prompt:
            payload["systemInstruction"] = {
                "parts": [{"text": system_prompt}]
            }

        # Native tool declarations or Google Search Grounding
        if tools:
            gemini_tools = to_gemini_tools(tools)
            if gemini_tools:
                payload["tools"] = gemini_tools
        elif enable_search:
            payload["tools"] = [{"googleSearch": {}}]

        return payload

    async def generate(
        self,
        messages: List[Dict[str, Any]],
        system_prompt: Optional[str] = None,
        temperature: float = 0.7,
        model_name: Optional[str] = None,
        media_parts: Optional[List[Dict[str, str]]] = None,
        image_parts: Optional[List[Dict[str, str]]] = None,
        enable_search: bool = False,
        thinking_enabled: bool = False
    ) -> str:
        if not self.api_key:
            raise ValueError("GEMINI_API_KEY is not set in environment.")

        target_model = model_name or self.default_model
        if not target_model.startswith("models/"):
            model_path = target_model
        else:
            model_path = target_model.replace("models/", "")

        url = f"https://generativelanguage.googleapis.com/v1beta/models/{model_path}:generateContent?key={self.api_key}"
        payload = self._prepare_payload(
            messages=messages,
            system_prompt=system_prompt,
            temperature=temperature,
            media_parts=media_parts,
            image_parts=image_parts,
            enable_search=enable_search,
            thinking_enabled=thinking_enabled
        )

        async with httpx.AsyncClient(timeout=600.0) as client:
            response = await client.post(url, json=payload)
            if response.status_code != 200:
                # If Google Search Grounding fails on specific unsupported model, retry without search tool
                if enable_search and response.status_code == 400:
                    payload.pop("tools", None)
                    response = await client.post(url, json=payload)

                if response.status_code != 200:
                    raise RuntimeError(f"Gemini API Error ({response.status_code}) for model {model_path}: {response.text}")

            data = response.json()
            try:
                candidate = data["candidates"][0]
                raw_text = candidate["content"]["parts"][0]["text"]
                clean_text = sanitize_response_output(raw_text)

                # Format citations if Google Search Grounding was active
                grounding_meta = candidate.get("groundingMetadata")
                return format_grounding_citations(clean_text, grounding_meta)
            except (KeyError, IndexError):
                raise RuntimeError(f"Unexpected response structure from Gemini API: {data}")

    async def generate_stream(
        self,
        messages: List[Dict[str, Any]],
        system_prompt: Optional[str] = None,
        temperature: float = 0.7,
        model_name: Optional[str] = None,
        media_parts: Optional[List[Dict[str, str]]] = None,
        image_parts: Optional[List[Dict[str, str]]] = None,
        enable_search: bool = False,
        thinking_enabled: bool = False
    ) -> AsyncGenerator[str, None]:
        if not self.api_key:
            raise ValueError("GEMINI_API_KEY is not set in environment.")

        target_model = model_name or self.default_model
        if not target_model.startswith("models/"):
            model_path = target_model
        else:
            model_path = target_model.replace("models/", "")

        url = f"https://generativelanguage.googleapis.com/v1beta/models/{model_path}:streamGenerateContent?key={self.api_key}&alt=sse"
        payload = self._prepare_payload(
            messages=messages,
            system_prompt=system_prompt,
            temperature=temperature,
            media_parts=media_parts,
            image_parts=image_parts,
            enable_search=enable_search,
            thinking_enabled=thinking_enabled
        )

        async with httpx.AsyncClient(timeout=600.0) as client:
            async with client.stream("POST", url, json=payload) as response:
                if response.status_code != 200:
                    error_text = await response.aread()
                    raise RuntimeError(f"Gemini Streaming Error ({response.status_code}): {error_text.decode()}")

                async for line in response.aiter_lines():
                    if line.startswith("data: "):
                        json_str = line[6:].strip()
                        if not json_str:
                            continue
                        import json
                        try:
                            data = json.loads(json_str)
                            text_chunk = data["candidates"][0]["content"]["parts"][0]["text"]
                            yield text_chunk
                        except (KeyError, IndexError, json.JSONDecodeError):
                            continue

    async def generate_agent_turn(
        self,
        messages: List[Dict[str, Any]],
        tools: Optional[List[Any]] = None,
        system_prompt: Optional[str] = None,
        temperature: float = 0.7,
        model_name: Optional[str] = None,
        media_parts: Optional[List[Dict[str, str]]] = None,
        image_parts: Optional[List[Dict[str, str]]] = None,
        thinking_enabled: bool = False,
    ) -> AgentModelTurn:
        """Normalized model step in the agent loop for Gemini function calling."""
        if not self.api_key:
            raise ValueError("GEMINI_API_KEY is not set in environment.")

        target_model = model_name or self.default_model
        model_path = target_model.replace("models/", "") if target_model.startswith("models/") else target_model

        url = f"https://generativelanguage.googleapis.com/v1beta/models/{model_path}:generateContent?key={self.api_key}"
        payload = self._prepare_payload(
            messages=messages,
            system_prompt=system_prompt,
            temperature=temperature,
            media_parts=media_parts,
            image_parts=image_parts,
            enable_search=False,
            thinking_enabled=thinking_enabled,
            tools=tools,
        )

        async with httpx.AsyncClient(timeout=600.0) as client:
            response = await client.post(url, json=payload)
            if response.status_code != 200:
                raise RuntimeError(f"Gemini Agent Turn Error ({response.status_code}) for model {model_path}: {response.text}")

            data = response.json()
            try:
                candidate = data["candidates"][0]
                parts = candidate.get("content", {}).get("parts", [])

                text_blocks: List[str] = []
                tool_calls: List[ToolCall] = []

                for idx, part in enumerate(parts):
                    if "functionCall" in part:
                        fc = part["functionCall"]
                        raw_name = fc.get("name", "")
                        canon_name = normalize_tool_call_name(raw_name)
                        args = fc.get("args") or {}
                        call_id = fc.get("id") or f"gemini_call_{idx+1}"
                        tool_calls.append(ToolCall(id=call_id, name=canon_name, arguments=args))
                    elif "text" in part:
                        text_blocks.append(part["text"])

                raw_text = "\n".join(text_blocks)
                clean_text = sanitize_response_output(raw_text) if raw_text else None

                return AgentModelTurn(
                    text=clean_text if clean_text else None,
                    tool_calls=tool_calls,
                    raw_metadata={"candidate": candidate}
                )
            except (KeyError, IndexError) as e:
                raise RuntimeError(f"Unexpected response structure from Gemini API: {data} ({e})")

